version: '3'

services:
  backend:
    build: ./
    container_name: backend
    working_dir: /backend
    ports:
      - ${API_PORT}:${API_PORT}
    env_file: .env
    platform: linux/x86_64
    restart: always
